name: flexi_image_slider
description: Image slider with auto scroll, dots indicator
version: 1.0.4
repository: https://github.com/Dharini17/flexi_image_slider

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dots_indicator: ^2.1.0
  cached_network_image: ^3.2.3
  gallery_zoom_slides: ^0.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

